# Scalars, vectors, matrices, tensors

<img src="./images/tensors.png" width = "500px">

<img src="./images/table-tensors.png" width = "500px">

## 1. Scalars

- No dimensions
- Single number
- Just magintude (value)
- Denoted in lowercase, italics, e.g.: *x*
- Should be typed, like other tensors: e.g.: int, float32

### Scalars (Rank 0 Tensors in Base Python)

In [26]:
x = 69
x

69

In [30]:
y = 1
py_sum = x + y
py_sum

70

In [32]:
type(py_sum)

int

In [38]:
float_x = float(x)
float_y = float(y)

float_sum = float_x + float_y
float_sum

70.0

In [40]:
type(float_sum)

float

In [46]:
mixed_sum =  x + float_y 
mixed_sum

70.0

In [48]:
type(mixed_sum)

float

### Scalars in PyTorch

In [61]:
import torch

In [67]:
x_pt = torch.tensor(420)
x_pt

tensor(420)

In [71]:
x_pt.shape

torch.Size([])

### Scalars in TensorFlow

In [76]:
import tensorflow as tf

In [84]:
x_tf = tf.Variable(25, dtype=tf.int16) #dtype optional
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [86]:
x_tf.shape

TensorShape([])

In [94]:
y_tf = tf.Variable(44, dtype=tf.int16)
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=69>

In [98]:
sum_tf = tf.add(x_tf, y_tf)
sum_tf

<tf.Tensor: shape=(), dtype=int16, numpy=69>

In [102]:
sum_tf.numpy()

69

## 2. Vectors
- One dimensional array of numbers
- Denoted in lowercase, italics, bold, e.g.: ***x***
- Arranged in an order, so element can be accessed by its index
- Elements in Vertors are scalars, (not bold) e.g.: *x$_1$*, *x$_2$* - elements of ***x***
- Vectors are representing a point in space:
  - Vectors of length two represents location in 2D matrix
  - Vectors of length three represents location in 3D cube
  - Length of *n* represents location in *n-dimensional* tensor

### Vectors (Rank 1 Tensors in NumPy)

In [123]:
import numpy as np

In [127]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [129]:
x.shape

(3,)

In [131]:
len(x)

3

In [133]:
x[0]

1

### Vector Transposition

In [141]:
x_t = x.T
x_t

array([1, 2, 3])

In [143]:
x.shape

(3,)

In [147]:
y = np.array([[1,2,3]])
y

array([[1, 2, 3]])

In [149]:
y.shape

(1, 3)

In [153]:
y_t = y.T
y_t

array([[1],
       [2],
       [3]])

In [155]:
y_t.shape

(3, 1)

In [161]:
y_t[2]

array([3])

### Vectors in PyTorch and TensorFlow

In [165]:
x_pt = torch.tensor([1,2,3])
x_pt

tensor([1, 2, 3])

In [176]:
x_tf = tf.Variable([1,2,3])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>

## 3. Norms of Vectors

### $L^2$ Norm


$$
\|x\|_2 = \sqrt{\sum_{i=1}^{n} |x_i|^2}
$$



### $L^2$ Norm in Python

In [215]:
vector = np.array([1,2,3])

v_sum = 0 
for i in vector:
    v_sum += i ** 2
v_sum ** (1/2)

3.7416573867739413

In [240]:
np.linalg.norm(vector)

3.7416573867739413

In [275]:
np.sum(vector**2)**(1/2)

3.7416573867739413

### Squared $L^2$ Norm

$$
\|x\|_2^2 = \sum_{i=1}^{n} |x_i|^2
$$


### Squared $L^2$ Norm in Python

In [269]:
vector = np.array([1,2,3])

v_sum = 0 
for i in vector:
    v_sum += i ** 2
v_sum 

14

In [271]:
np.dot(vector.T, vector)

14

In [273]:
np.sum(vector**2)

14

### $L^1$ Norm

$$
\|x\|_1 = \sum_{i=1}^{n} |x_i|
$$

In [287]:
vector = np.array([1,2,3])

v_sum = 0 
for i in vector:
    v_sum += abs(i) 
v_sum 


6

In [291]:
np.sum(abs(vector))

6

### Max Norm ($L^\infty$)

$$
\|x\|_\infty = \max(|x_i|)
$$

In [304]:
vector = np.array([1,2,3])

max(abs(vector))

3

### Generalized $L^p$ notation

$$
\|x\|_p = \left(\sum_{i=1}^{n} |x_i|^p)\right)^{\frac{1}{p}}
$$

### Orthogonl Vectors

$$
x^T\cdot y = 0
$$

In [347]:
x = np.array([0,1])
y = np.array([1,0])

np.dot(x,y)

0

## 3. Matrices

- Two dimensional array of numbers
- Denoted in uppercase, italics, bold, e.g.: ***X***
- Individual scalar elements denoted in uppercase, italics only
- Colon represents an entrie row or column:
  - Left column of matrix ***X*** is ***$X_{:,1}$***
  - Middle row of Matrix ***X*** is ***$X_{2,:}$***

### Matrices (Rank 2 Tensors) in NumPy

In [363]:
X = np.array([[1,2,3], [4,5,6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [367]:
X.shape

(2, 3)

In [369]:
X.size

6

In [371]:
X.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [377]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [381]:
X[0,2]

3

In [383]:
X[:,1]

array([2, 5])

In [385]:
X[1,:]

array([4, 5, 6])

In [395]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [407]:
X[0:3, 1:3]

array([[2, 3],
       [5, 6]])

In [411]:
X[0:, 1:]

array([[2, 3],
       [5, 6]])

## Matrices in PyTorch

In [416]:
X_pt = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
X_pt.shape

torch.Size([3, 3])

## Matrices in TensorFlow

In [429]:
X_tf = tf.Variable([[1,2], [3,4], [5,6]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [431]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## 4. Higher-Rank Tensors

In [436]:
images_pt = torch.zeros([32,28,28,3])
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.